# Etapa 1: Compilación
FROM golang:1.22-alpine AS builder

WORKDIR /app

# Copiar dependencias
COPY go.mod go.sum ./
RUN go mod download

# Copiar código fuente
COPY . .

# Compilar el binario
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Etapa 2: Imagen final ligera
FROM alpine:latest

WORKDIR /app

# Copiar el ejecutable desde la etapa previa
COPY --from=builder /app/main .

# Copiar carpeta static si la utilizas
COPY --from=builder /app/static ./static

EXPOSE 8080

CMD ["./main"]